
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.crrl.lexical.lexer;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int AND = 3;
  public static final int NOT = 2;
  public static final int error = 1;
  public static final int P_OPEN = 5;
  public static final int B_EXP = 7;
  public static final int OR = 4;
  public static final int EOF = 0;
  public static final int P_CLOSE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NOT",
  "AND",
  "OR",
  "P_OPEN",
  "P_CLOSE",
  "B_EXP"
  };
}

